import type { Metadata } from "next";
import { Geist, Geist_Mono, DM_Serif_Display } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/Header"; // Import your Header component
import Footer from "@/components/Footer"; // Import your Footer component
import React from 'react'; // Import React if not already present

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const dmSerifDisplay = DM_Serif_Display({
  variable: "--font-dm-serif-display",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${dmSerifDisplay.variable} antialiased flex flex-col min-h-screen`} // Added flex and min-h-screen
      >
        <Header /> {/* Include the Header */}
        <main className="flex-grow pt-12"> {/* Added main and flex-grow */}
          {children}
        </main>
        <Footer /> {/* Include the Footer */}
      </body>
    </html>
  );
}